version: '2.1'
services:
  nebula:
    image: aaronkollasch/nebula:1.0
    container_name: nebula
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=UTC
    entrypoint:
      - /nebula
      - -config
      - /etc/nebula/config.lighthouse.yaml
    volumes:
      - /etc/nebula:/etc/nebula:ro
    restart: always

