version: '2.1'
services:
  nebula:
    image: nebula
    container_name: nebula
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Europe/London
    entrypoint:
      - /nebula
      - -config
      - /volume1/nebula/config.yaml
    volumes:
      - /volume1/nebula:/volume1/nebula:ro
    restart: always

